name: Bulid dev version
on:
  push:
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Python GUI With TkInter
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          mode: standalone
          enable-plugins: tk-inter
          windows-console-mode: attach
          windows-icon-from-ico: favicon.ico
          linux-icon: favicon.ico

      - name: Pack
        run: |
          mkdir pub
          copy ${{ github.workspace }}/build ${{ github.workspace }}/pub
          copy ${{ github.workspace }}/NamePicker.png ${{ github.workspace }}/pub
          copy ${{ github.workspace }}/favicon.ico ${{ github.workspace }}/pub

      - name: Upload Artifacts
        if: ${{ matrix.os }} == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: NamePicker-Action-${{ runner.os }}
          path: |
            ${{ github.workspace }}/pub
          include-hidden-files: true

  build_linux:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Python GUI With TkInter
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          mode: standalone
          enable-plugins: tk-inter
          windows-console-mode: attach
          windows-icon-from-ico: favicon.ico
          linux-icon: favicon.ico

      - name: Pack
        if: ${{ matrix.os }} == 'ubuntu-latest'
        run: |
          mkdir pub
          mv ${{ github.workspace }}/build ${{ github.workspace }}/pub
          mv ${{ github.workspace }}/NamePicker.png ${{ github.workspace }}/pub
          mv ${{ github.workspace }}/favicon.ico ${{ github.workspace }}/pub

      - name: Upload Artifacts
        if: ${{ matrix.os }} == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: NamePicker-Action-${{ runner.os }}
          path: |
            ${{ github.workspace }}/pub
          include-hidden-files: true