name: Bulid dev version
on:
  push:
    branches:
      - rinui
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    outputs:
      artiid: ${{ steps.artifact-upload-step.outputs.artifact-id }}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install -i https://test.pypi.org/simple/ RinUI --no-deps

      - name: Build Executable
        run: pyinstaller main.spec

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: NamePicker-Action-${{ runner.os }}
          path: |
            ${{ github.workspace }}/dist/main
          include-hidden-files: true

  release:
    needs: [build_matrix]
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4
      - name: Prepare release
        run: |
          mkdir release
          mkdir artifacts
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          run-id: ${{needs.build_matrix.outputs.artiid}}
      - name: Prepare artifacts
        run: |
          mv artifacts/NamePicker-Actions-Windows release/
          mv artifacts/NamePicker-Actions-Linux release/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
          body_path: CHANGELOG.md
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
